### ISSUE TITLE
hbitmap is leaking in ContextMenuExtractTo

### ISSUE THREAD

**Issue by chrdavis** [XiaoFaye/ZipFolderEx#1]
DeleteObject needs to be called in ContextMenuExtractTo::~ContextMenuExtractTo on hbitmap

**Comment by XiaoFaye** [comment]
Thanks for the tips!  Commit https://github.com/XiaoFaye/ZipFolderEx/commit/1fca590c9bfcd29ac08f68530014bac5063996c6 has fixed this issue.

**Comment by chrdavis** [comment]
lgtm
